# Generated by Django 5.0.6 on 2024-06-04 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id_campus', models.AutoField(primary_key=True, serialize=False)),
                ('nome_campus', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dimensao',
            fields=[
                ('id_dim', models.AutoField(primary_key=True, serialize=False)),
                ('nome_dim', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id_eixo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_eixo', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tipo', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publico',
            fields=[
                ('id_publico', models.AutoField(primary_key=True, serialize=False)),
                ('nome_publico', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('id_campus', models.ForeignKey(blank=True, db_column='id_campus', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpasisApp.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id_indicador', models.AutoField(primary_key=True, serialize=False)),
                ('nome_indicador', models.TextField(blank=True, max_length=200, null=True, unique=True)),
                ('nota_indicador', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('id_curso', models.ForeignKey(blank=True, db_column='id_curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpasisApp.curso')),
                ('id_dim', models.ForeignKey(blank=True, db_column='id_dim', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpasisApp.dimensao')),
                ('id_eixo', models.ForeignKey(blank=True, db_column='id_eixo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpasisApp.eixo')),
                ('id_pub', models.ForeignKey(blank=True, db_column='id_publico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpasisApp.publico')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='id_tipo',
            field=models.ForeignKey(blank=True, db_column='id_tipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpasisApp.tipocurso'),
        ),
    ]
