# Generated by Django 5.0.6 on 2024-06-06 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpasisApp', '0003_publico_id_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='id_campus',
            field=models.ForeignKey(blank=True, db_column='id_campus', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cpasisApp.campus'),
        ),
    ]
